initial commit
SFDigitalServices/ooc-permit-list-sd-mspy pull request #1
Opened 2019-02-20 18:58 UTC by hshaosf

2019-02-25 23:47 UTC, josh-chou requested changes

2019-02-25 23:47 UTC, josh-chou commented on .circleci/config.yml
> +            source .env.example
Should we be sourcing the .env.example?

2019-02-25 23:47 UTC, josh-chou commented on service/resources/permit_list.py
> +            params['advanced_search'] = '%5B%7B"name"%3A"forms"%2C"method"%3A"is"%2C"value"%3A5804%7D%2C%7B"name"%3A"rfdd8a5g7g"%2C"method"%3A"is_any"%2C"value"%3A%5B"retailer+(medicinal+and+adult+us
is there a python method we can use to url encode the string instead of doing it manually?

2019-02-25 23:47 UTC, josh-chou commented on service/microservice.py
> +    sentry_sdk.init(
what if SENTRY_DSN not set?  Does this blow up?

2019-02-25 23:47 UTC, josh-chou commented on service/resources/permit_list.py
> +                if resp.get('responses', False) and resp['responses'].get('dd8a5g7g', False):
These strings should get assigned to a variable/constant?
This one in particular is used more than once.

2019-02-25 23:54 UTC, hshaosf commented on service/resources/permit_list.py
> +            params['advanced_search'] = '%5B%7B"name"%3A"forms"%2C"method"%3A"is"%2C"value"%3A5804%7D%2C%7B"name"%3A"rfdd8a5g7g"%2C"method"%3A"is_any"%2C"value"%3A%5B"retailer+(medicinal+and+adult+us
The string is pulled off screendoor's interface, and the structure is not well documented.   Given it's not a well-documented structure and it might change, I'm using it as is. 

From: http://dobtco.github.io/screendoor-api-docs/#responses
> To find the correct parameters, consider using advanced search to construct a query. Then copy the ?advanced_search= part of the resulting URL.

2019-02-25 23:55 UTC, hshaosf commented on .circleci/config.yml
> +            source .env.example
Yes, this is to load the necessary placeholder environment variable for CI testing.

2019-02-25 23:57 UTC, hshaosf commented on service/microservice.py
> +    sentry_sdk.init(
That's why in CI config, it sources at least an example environmental variable.  We could put a check, but given that it is a required environmental variable, I'm of opinion that should blow up if someone did not set it to make it obvious. But happy to discuss and/or create ADR how we should handle require/non-required environmental variables.

2019-02-26 00:03 UTC, josh-chou commented on .circleci/config.yml
> +            source .env.example
Shouldn't it be .env and not the example file?

2019-02-26 00:05 UTC, hshaosf commented on service/resources/permit_list.py
> +                if resp.get('responses', False) and resp['responses'].get('dd8a5g7g', False):
I concurred once the form fields are finalized.  It isn't yet at the moment.

2019-02-26 00:12 UTC, josh-chou commented on service/microservice.py
> +    sentry_sdk.init(
From the comment, I would think the SENTRY_DSN is optional.  If I don't set it, then no Sentry monitoring.
If it is required, then I agree it should blow up.

2019-02-26 00:13 UTC, hshaosf commented on .circleci/config.yml
> +            source .env.example
It is just loading placeholders to simulate the environment, the actual variable is with the environment itself.  And test running is with mock data to test codes are control, otherwise, if we added 3rd party service we do not control, we could end up with an inconsistent result due to external factors.  

Future state, we would create separate testing suites outside of this repo to test the 3rd party services to make sure we are getting the responses we are expecting.  This would help not block our own code development workflow within repo if a 3rd party service is down.

2019-02-26 00:15 UTC, hshaosf commented on service/microservice.py
> +    sentry_sdk.init(
This is defined with app.json. 

https://github.com/SFDigitalServices/ooc-permit-list-sd-mspy/blob/69ab8c009fd6d10faa7b5c84522252399f8ef087/app.json#L21-L23

2019-02-26 00:19 UTC, hshaosf commented on service/microservice.py
> +    sentry_sdk.init(
An example optional env var is `SENTRY_DSN_PRODUCTION`.  It won't blow up if someone decides to use the same Sentry DNS for both production and testing/development environments.

2019-02-26 00:31 UTC, josh-chou commented on .circleci/config.yml
> +            source .env.example
It is expected that the engineer creates a copy of .env.example and creates a .env file with values modified as needed?  By sourcing the .example file, it's no longer an example.  It becomes a requirement.  Maybe just rename the file to .env in that case.

2019-02-26 00:35 UTC, josh-chou commented on service/microservice.py
> +    sentry_sdk.init(
I'm confused.  How does the setting in app.json affect the code?
If I set required:false in app.json, and don't set SENTRY_DSN environment var, will it blow up?

2019-02-26 00:38 UTC, hshaosf commented on service/microservice.py
> +    sentry_sdk.init(
Heroku looks at app.json to construct the environment. if you set it to false, the instance Heroku setup will have an error.

2019-02-26 00:45 UTC, josh-chou commented on service/microservice.py
> +    sentry_sdk.init(
So SENTRY_DSN is basically required.  It should blow up.

2019-02-26 00:57 UTC, hshaosf commented on service/microservice.py
> +    sentry_sdk.init(
> So SENTRY_DSN is basically required. It should blow up.

I stand corrected. `SENTRY_DSN` is optional.  I'll check in new .env.example to be more explicit.

2019-02-26 01:06 UTC, hshaosf commented on .circleci/config.yml
> +            source .env.example
> It is expected that the engineer creates a copy of .env.example and creates a .env file with values modified as needed? By sourcing the .example file, it's no longer an example. It becomes a requirement. Maybe just rename the file to .env in that case.

Checked in 71c313bb5283073dbe90ccb84c6c84b612a611da to simulate this action.

2019-02-26 19:58 UTC, josh-chou approved these changes

2019-02-27 18:21 UTC, merged